### ISSUE TITLE
difflib.js:150 Uncaught (in promise) TypeError: isjunk is not a function

### ISSUE THREAD

**Issue by dibollinger** [Fredilein/CookieAudit#1]
Tested on 6f0b278a

When I go to ```purplemath.com``` and accept the cookiebanner there, it creates a consent cookie, and the extension crashes due to the following error:

```
background.js:28 Successfully connected to CookieDB.
cmp.js:14 CookieConsent  -  www.purplemath.com
cmp.js:15 {stamp:%277MH7fYdS2wVPCyBH06w2qrBd3YAdqz2Rep5ql/lGfMeUcbzUgmKS9Q==%27%2Cnecessary:true%2Cpreferences:true%2Cstatistics:true%2Cmarketing:true%2Cver:3%2Cutc:1659163737808%2Cregion:%27it%27}
cmp.js:17 (4) ['necessary', 'preferences', 'statistics', 'marketing']
difflib.js:150 Uncaught (in promise) TypeError: isjunk is not a function
    at SequenceMatcher.__chain_b (difflib.js:150:37)
    at SequenceMatcher.set_seq2 (difflib.js:111:9)
    at SequenceMatcher.set_seqs (difflib.js:98:9)
    at new SequenceMatcher (difflib.js:406:8)
    at feature_gestalt_mean_and_stddev (extractor.js:394:15)
    at extractFeatures (extractor.js:911:7)
    at classifyCookie (background.js:270:18)
    at handleCookie (background.js:338:24)
SequenceMatcher.__chain_b @ difflib.js:150
SequenceMatcher.set_seq2 @ difflib.js:111
SequenceMatcher.set_seqs @ difflib.js:98
SequenceMatcher @ difflib.js:406
feature_gestalt_mean_and_stddev @ extractor.js:394
extractFeatures @ extractor.js:911
classifyCookie @ background.js:270
handleCookie @ background.js:338
await in handleCookie (async)
(anonymous) @ background.js:363
```
I believe this is because of the Manifestv3 conversion. Something within the difflib.js file isn't working anymore.

A bandaid fix would be to disable the feature in question. (gestalt_mean_and_stddev).

**Comment by Fredilein** [comment]
This is now fixed.

Commit: https://github.com/Fredilein/CookieAudit/commit/97035dc270cf65a5660fc4bded53656cf5afe9cf
